@startuml
'https://plantuml.com/class-diagram

class Main
class Calculator
class Stack
class InfixTranslator

interface ICalculator
interface IStack

Main "uses" ..> ICalculator
Calculator .|> ICalculator
Calculator "uses" ..> IStack
Calculator *-left-> InfixTranslator
Stack .|> IStack

@enduml